[package]
name = "scroll-sc-tools"
version = "0.1.0"
edition = "2024"

[dependencies]

# openvm
openvm-native-recursion = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.4.0", default-features = false }
openvm-sdk = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.4.0", default-features = false, features = [
  "parallel",
  "evm-prove",
  "evm-verify",
  "tco",
  "unprotected",
] }
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", tag = "v1.2.1" }

# revm
revm = "=24.0.0"

# snark-verifier
snark-verifier-sdk = { version = "=0.2.1", default-features = false, features = [
  "loader_halo2",
  "halo2-axiom",
  "display",
] }

# scroll-tech/zkvm-prover
scroll-zkvm-verifier = { git = "ssh://github.com/scroll-tech/zkvm-prover-issue", rev = "fa943eb53ee7c9dcd5966c6df4a7dbc5e15bc3ed" }

# miscellaneous
clap = "4"
eyre = "0.6"
hex = "0.4"
reqwest = { version = "0.12", features = ["blocking"] }

[patch.crates-io]
revm = { git = "https://github.com/scroll-tech/revm", tag = "scroll-v91" }
revm-bytecode = { git = "https://github.com/scroll-tech/revm", tag = "scroll-v91" }
revm-context = { git = "https://github.com/scroll-tech/revm", tag = "scroll-v91" }
revm-context-interface = { git = "https://github.com/scroll-tech/revm", tag = "scroll-v91" }
revm-database = { git = "https://github.com/scroll-tech/revm", tag = "scroll-v91" }
revm-database-interface = { git = "https://github.com/scroll-tech/revm", tag = "scroll-v91" }
revm-handler = { git = "https://github.com/scroll-tech/revm", tag = "scroll-v91" }
revm-inspector = { git = "https://github.com/scroll-tech/revm", tag = "scroll-v91" }
revm-interpreter = { git = "https://github.com/scroll-tech/revm", tag = "scroll-v91" }
revm-precompile = { git = "https://github.com/scroll-tech/revm", tag = "scroll-v91" }
revm-primitives = { git = "https://github.com/scroll-tech/revm", tag = "scroll-v91" }
revm-state = { git = "https://github.com/scroll-tech/revm", tag = "scroll-v91" }
